print("""
PRASANTH MALLA
NOVEMBER 17 2022
I AM SIGNING UP FOR REPLIT'S 100 DAYS OF PYTHON CHALLENGE!
I WILL MAKE SURE TO SPEND SOME TIME EVERYDAY CODING ALONG,FOR A MINIMUM OF 10 MINUTES A DAY.
I'LL BE USING REPLIT , AN AMAZING ONLINE IDE SO I CAN DO THIS FROM MY PHONE WHEREVER I HAPPPEN TO BE. NO EXCUSES FOR NOT CODING FROM THE MIDDLE OF A FIELD!
I AM FEELING 🤩
YOU CAN FOLLOW MY PROGRESS AT REPLIT.COM/@MALLANAGA
""")
